# Header
menu:
  Home: /
  # Delete this row if you don't want categories in your header nav bar
  Categories:
  About: http://www.vviana.com

# Content
fancybox: true

# Thumbnail
thumbnail: true

# Scroll Loading
scrollLoading: true

# Sidebar
social_links:
  twitter: https://twitter.com/masterviana
  facebook:
  google_plus: https://plus.google.com/104595400231096231256/posts
  github: https://github.com/masterviana
  weibo:
  rss: /atom.xml
widgets:
- recent_posts
- category
- archive
- tag
- tagcloud
- links

# Links
links:
  Website: http://www.vviana.com

# Miscellaneous
google_analytics: UA-60110561-1
favicon: /favicon.png
fb_admins:
fb_app_id:
